version: "3.8"

name: livepeer-exporter

services:
  livepeer-exporter:
    build: .
    image: livepeer-exporter
    container_name: livepeer-exporter
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro" # Set timezone to host timezone.
      - "/etc/localtime:/etc/localtime:ro" # Set time to host time.
    ports:
      - "9153:9153"
    environment:
      LIVEPEER_EXPORTER_ORCHESTRATOR_ADDRESS: "<YOUR_ORCHESTRATOR_ADDRESS>"
      LIVEPEER_EXPORTER_ORCHESTRATOR_ADDRESS_SECONDARY: "<YOUR_SECONDARY_ORCHESTRATOR_ADDRESS>"
      LIVEPEER_EXPORTER_FETCH_INTERVAL: "5m"
      LIVEPEER_EXPORTER_FETCH_TEST_STREAMS_INTERVAL: "15m"
      LIVEPEER_EXPORTER_TICKETS_FETCH_INTERVAL: "1h"
      LIVEPEER_EXPORTER_REWARDS_FETCH_INTERVAL: "12h"
      LIVEPEER_EXPORTER_UPDATE_INTERVAL: "30s"

networks:
  default:
    name: livepeer
    external: true
